version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste123
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
 
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: teste123
      PGDATABASE: user_db
